wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.5
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.7
dataset:
  desc: null
  value: AlzheimerT2SmallDataset
experiment_group:
  desc: null
  value: null
gpu_ind:
  desc: null
  value: 0
model:
  desc: null
  value: MultiClassCNN
network:
  desc: null
  value: vgg16
train_args:
  desc: null
  value:
    batch_size: 8
    epochs: 10
